### ISSUE TITLE
Consultant

### ISSUE THREAD

**Issue by Centonni** [Mariame12/FicheAbsence#1]
package com.projet.domain;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * A Consultant.
 */
@Entity
@Table(name = "consultant")
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
public class Consultant implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "nom")
    private String nom;

    @Column(name = "prenom")
    private String prenom;

    @Column(name = "fonction")
    private String fonction;

    @ManyToOne
    @JsonIgnoreProperties(value = { "consultants" }, allowSetters = true)
    private Prestataire prestataire;

    @OneToMany(mappedBy = "consultant")
    @Cache(usage = CacheConcurrencyStrategy.READ_WRITE)
    @JsonIgnoreProperties(value = { "consultant" }, allowSetters = true)
    private Set<FichePresence> fichePresences = new HashSet<>();

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Consultant id(Long id) {
        this.id = id;
        return this;
    }

    public String getNom() {
        return this.nom;
    }

    public Consultant nom(String nom) {
        this.nom = nom;
        return this;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public Consultant prenom(String prenom) {
        this.prenom = prenom;
        return this;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getFonction() {
        return this.fonction;
    }

    public Consultant fonction(String fonction) {
        this.fonction = fonction;
        return this;
    }

    public void setFonction(String fonction) {
        this.fonction = fonction;
    }

    public Prestataire getPrestataire() {
        return this.prestataire;
    }

    public Consultant prestataire(Prestataire prestataire) {
        this.setPrestataire(prestataire);
        return this;
    }

    public void setPrestataire(Prestataire prestataire) {
        this.prestataire = prestataire;
    }

    public Set<FichePresence> getFichePresences() {
        return this.fichePresences;
    }

    public Consultant fichePresences(Set<FichePresence> fichePresences) {
        this.setFichePresences(fichePresences);
        return this;
    }

    public Consultant addFichePresence(FichePresence fichePresence) {
        this.fichePresences.add(fichePresence);
        fichePresence.setConsultant(this);
        return this;
    }

    public Consultant removeFichePresence(FichePresence fichePresence) {
        this.fichePresences.remove(fichePresence);
        fichePresence.setConsultant(null);
        return this;
    }

    public void setFichePresences(Set<FichePresence> fichePresences) {
        if (this.fichePresences != null) {
            this.fichePresences.forEach(i -> i.setConsultant(null));
        }
        if (fichePresences != null) {
            fichePresences.forEach(i -> i.setConsultant(this));
        }
        this.fichePresences = fichePresences;
    }

    // jhipster-needle-entity-add-getters-setters - JHipster will add getters and setters here

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Consultant)) {
            return false;
        }
        return id != null && id.equals(((Consultant) o).id);
    }

    @Override
    public int hashCode() {
        // see https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/
        return getClass().hashCode();
    }

    // prettier-ignore
    @Override
    public String toString() {
        return getNom() +" "+getPrenom();
    }
}

**Comment by Centonni** [comment]
package com.projet.web.rest;

import com.opencsv.CSVWriter;
import com.opencsv.bean.StatefulBeanToCsv;
import com.opencsv.bean.StatefulBeanToCsvBuilder;
import com.projet.domain.FichePresence;
import com.projet.repository.FichePresenceRepository;
import com.projet.service.FichePresenceQueryService;
import com.projet.service.FichePresenceService;
import com.projet.service.criteria.FichePresenceCriteria;
import com.projet.service.impl.ExportService;
import com.projet.web.rest.errors.BadRequestAlertException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;
import tech.jhipster.web.util.HeaderUtil;
import tech.jhipster.web.util.PaginationUtil;
import tech.jhipster.web.util.ResponseUtil;

/**
 * REST controller for managing {@link com.projet.domain.FichePresence}.
 */
@RestController
@RequestMapping("/api")
public class FichePresenceResource {

    private final Logger log = LoggerFactory.getLogger(FichePresenceResource.class);

    private static final String ENTITY_NAME = "fichePresence";

    @Value("${jhipster.clientApp.name}")
    private String applicationName;

    private final FichePresenceService fichePresenceService;

    private final FichePresenceRepository fichePresenceRepository;

    private final FichePresenceQueryService fichePresenceQueryService;
    private final ExportService exportService;

    public FichePresenceResource(
        FichePresenceService fichePresenceService,
        FichePresenceRepository fichePresenceRepository,
        FichePresenceQueryService fichePresenceQueryService,
        ExportService exportService
    ) {
        this.fichePresenceService = fichePresenceService;
        this.fichePresenceRepository = fichePresenceRepository;
        this.fichePresenceQueryService = fichePresenceQueryService;
        this.exportService = exportService;
    }

    /**
     * {@code POST  /fiche-presences} : Create a new fichePresence.
     *
     * @param fichePresence the fichePresence to create.
     * @return the {@link ResponseEntity} with status {@code 201 (Created)} and with body the new fichePresence, or with status {@code 400 (Bad Request)} if the fichePresence has already an ID.
     * @throws URISyntaxException if the Location URI syntax is incorrect.
     */
    @PostMapping("/fiche-presences")
    public ResponseEntity<FichePresence> createFichePresence(@RequestBody FichePresence fichePresence) throws URISyntaxException {
        log.debug("REST request to save FichePresence : {}", fichePresence);
        if (fichePresence.getId() != null) {
            throw new BadRequestAlertException("A new fichePresence cannot already have an ID", ENTITY_NAME, "idexists");
        }
        FichePresence result = fichePresenceService.save(fichePresence);
        return ResponseEntity
            .created(new URI("/api/fiche-presences/" + result.getId()))
            .headers(HeaderUtil.createEntityCreationAlert(applicationName, true, ENTITY_NAME, result.getId().toString()))
            .body(result);
    }

    /**
     * {@code PUT  /fiche-presences/:id} : Updates an existing fichePresence.
     *
     * @param id the id of the fichePresence to save.
     * @param fichePresence the fichePresence to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated fichePresence,
     * or with status {@code 400 (Bad Request)} if the fichePresence is not valid,
     * or with status {@code 500 (Internal Server Error)} if the fichePresence couldn't be updated.
     * @throws URISyntaxException if the Location URI syntax is incorrect.
     */
    @PutMapping("/fiche-presences/{id}")
    public ResponseEntity<FichePresence> updateFichePresence(
        @PathVariable(value = "id", required = false) final Long id,
        @RequestBody FichePresence fichePresence
    ) throws URISyntaxException {
        log.debug("REST request to update FichePresence : {}, {}", id, fichePresence);
        if (fichePresence.getId() == null) {
            throw new BadRequestAlertException("Invalid id", ENTITY_NAME, "idnull");
        }
        if (!Objects.equals(id, fichePresence.getId())) {
            throw new BadRequestAlertException("Invalid ID", ENTITY_NAME, "idinvalid");
        }

        if (!fichePresenceRepository.existsById(id)) {
            throw new BadRequestAlertException("Entity not found", ENTITY_NAME, "idnotfound");
        }

        FichePresence result = fichePresenceService.save(fichePresence);
        return ResponseEntity
            .ok()
            .headers(HeaderUtil.createEntityUpdateAlert(applicationName, true, ENTITY_NAME, fichePresence.getId().toString()))
            .body(result);
    }

    /**
     * {@code PATCH  /fiche-presences/:id} : Partial updates given fields of an existing fichePresence, field will ignore if it is null
     *
     * @param id the id of the fichePresence to save.
     * @param fichePresence the fichePresence to update.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the updated fichePresence,
     * or with status {@code 400 (Bad Request)} if the fichePresence is not valid,
     * or with status {@code 404 (Not Found)} if the fichePresence is not found,
     * or with status {@code 500 (Internal Server Error)} if the fichePresence couldn't be updated.
     * @throws URISyntaxException if the Location URI syntax is incorrect.
     */
    @PatchMapping(value = "/fiche-presences/{id}", consumes = "application/merge-patch+json")
    public ResponseEntity<FichePresence> partialUpdateFichePresence(
        @PathVariable(value = "id", required = false) final Long id,
        @RequestBody FichePresence fichePresence
    ) throws URISyntaxException {
        log.debug("REST request to partial update FichePresence partially : {}, {}", id, fichePresence);
        if (fichePresence.getId() == null) {
            throw new BadRequestAlertException("Invalid id", ENTITY_NAME, "idnull");
        }
        if (!Objects.equals(id, fichePresence.getId())) {
            throw new BadRequestAlertException("Invalid ID", ENTITY_NAME, "idinvalid");
        }

        if (!fichePresenceRepository.existsById(id)) {
            throw new BadRequestAlertException("Entity not found", ENTITY_NAME, "idnotfound");
        }

        Optional<FichePresence> result = fichePresenceService.partialUpdate(fichePresence);

        return ResponseUtil.wrapOrNotFound(
            result,
            HeaderUtil.createEntityUpdateAlert(applicationName, true, ENTITY_NAME, fichePresence.getId().toString())
        );
    }

    /**
     * {@code GET  /fiche-presences} : get all the fichePresences.
     *
     * @param pageable the pagination information.
     * @param criteria the criteria which the requested entities should match.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the list of fichePresences in body.
     * @throws Exception
     */
    @GetMapping("/fiche-presences")
    public ResponseEntity<List<FichePresence>> getAllFichePresences(FichePresenceCriteria criteria, Pageable pageable) throws Exception {
        log.debug("REST request to get FichePresences by criteria: {}", criteria);
        Page<FichePresence> page = fichePresenceQueryService.findByCriteria(criteria, pageable);
        HttpHeaders headers = PaginationUtil.generatePaginationHttpHeaders(ServletUriComponentsBuilder.fromCurrentRequest(), page);

        return ResponseEntity.ok().headers(headers).body(page.getContent());
    }

    /**
     * {@code GET  /fiche-presences/export} : count all the fichePresences.
     *
     * @param criteria the criteria which the requested entities should match.
     * @throws Exception
     */

    @GetMapping("/fiche-presences/export/{id}")
    public void ExportFic(@PathVariable("id") Long idConsultant,HttpServletResponse response) throws Exception {
        //set file name and content type
        String filename = "fiches.csv";

        response.setContentType("text/csv");
        response.setHeader(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + filename + "\"");

        //create a csv writer
        StatefulBeanToCsv<FichePresence> writer = new StatefulBeanToCsvBuilder<FichePresence>(response.getWriter())
            .withQuotechar(CSVWriter.NO_QUOTE_CHARACTER)
            .withSeparator(CSVWriter.DEFAULT_SEPARATOR)
            .withOrderedResults(false)
            .build();

        //write all users to csv file
        writer.write(exportService.ExportFiche(idConsultant));
    }

    /**
     * {@code GET  /fiche-presences/count} : count all the fichePresences.
     *
     * @param criteria the criteria which the requested entities should match.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and the count in body.
     */
    @GetMapping("/fiche-presences/count")
    public ResponseEntity<Long> countFichePresences(FichePresenceCriteria criteria) {
        log.debug("REST request to count FichePresences by criteria: {}", criteria);
        return ResponseEntity.ok().body(fichePresenceQueryService.countByCriteria(criteria));
    }

    /**
     * {@code GET  /fiche-presences/:id} : get the "id" fichePresence.
     *
     * @param id the id of the fichePresence to retrieve.
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body the fichePresence, or with status {@code 404 (Not Found)}.
     */
    @GetMapping("/fiche-presences/{id}")
    public ResponseEntity<FichePresence> getFichePresence(@PathVariable Long id) {
        log.debug("REST request to get FichePresence : {}", id);
        Optional<FichePresence> fichePresence = fichePresenceService.findOne(id);
        return ResponseUtil.wrapOrNotFound(fichePresence);
    }

    /**
     * {@code DELETE  /fiche-presences/:id} : delete the "id" fichePresence.
     *
     * @param id the id of the fichePresence to delete.
     * @return the {@link ResponseEntity} with status {@code 204 (NO_CONTENT)}.
     */
    @DeleteMapping("/fiche-presences/{id}")
    public ResponseEntity<Void> deleteFichePresence(@PathVariable Long id) {
        log.debug("REST request to delete FichePresence : {}", id);
        fichePresenceService.delete(id);
        return ResponseEntity
            .noContent()
            .headers(HeaderUtil.createEntityDeletionAlert(applicationName, true, ENTITY_NAME, id.toString()))
            .build();
    }
}

**Comment by Centonni** [comment]
`<div>
  <h2 id="page-heading" data-cy="FichePresenceHeading">
    <span jhiTranslate="projetApp.fichePresence.home.title">Fiche Absences</span>

    <div class="d-flex justify-content-end">
      <button class="btn btn-success">
        <fa-icon icon="save" [spin]="isLoading"></fa-icon>
        <a target="_blank" href="http://localhost:8080/api/fiche-presences/export/">
          <span>Exporter </span>
        </a>
      </button>

      <button class="btn btn-info mr-2" (click)="reset()" [disabled]="isLoading">
        <fa-icon icon="sync" [spin]="isLoading"></fa-icon>
        <span jhiTranslate="projetApp.fichePresence.home.refreshListLabel">Refresh List</span>
      </button>

      <button
        id="jh-create-entity"
        data-cy="entityCreateButton"
        class="btn btn-primary jh-create-entity create-fiche-presence"
        [routerLink]="['/fiche-presence/new']"
      >
        <fa-icon icon="plus"></fa-icon>
        <span jhiTranslate="projetApp.fichePresence.home.createLabel"> Create a new Fiche Absence </span>
      </button>
    </div>
  </h2>

  <jhi-alert-error></jhi-alert-error>

  <jhi-alert></jhi-alert>

  <div class="alert alert-warning" id="no-result" *ngIf="fichePresences?.length === 0">
    <span jhiTranslate="projetApp.fichePresence.home.notFound">No ficheAbsences found</span>
  </div>

  <div class="table-responsive" id="entities" *ngIf="fichePresences && fichePresences.length > 0">
    <table class="table table-striped" aria-describedby="page-heading">
      <thead>
        <tr jhiSort [(predicate)]="predicate" [(ascending)]="ascending" [callback]="reset.bind(this)">
          <th scope="col" jhiSortBy="id"><span jhiTranslate="global.field.id">ID</span> <fa-icon icon="sort"></fa-icon></th>
          <th scope="col" jhiSortBy="activites">
            <span jhiTranslate="projetApp.fichePresence.activites">Activites</span> <fa-icon icon="sort"></fa-icon>
          </th>

          <th scope="col" jhiSortBy="commentaire">
            <span jhiTranslate="projetApp.fichePresence.commentaire">Commentaire</span> <fa-icon icon="sort"></fa-icon>
          </th>

          <th scope="col" jhiSortBy="date">
            <span jhiTranslate="projetApp.fichePresence.date">Date</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col" jhiSortBy="consultant.id">
            <span jhiTranslate="projetApp.fichePresence.consultant">Consultant</span> <fa-icon icon="sort"></fa-icon>
          </th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody infinite-scroll (scrolled)="loadPage(page + 1)" [infiniteScrollDisabled]="page >= links['last']" [infiniteScrollDistance]="0">
        <tr *ngFor="let fichePresence of fichePresences; trackBy: trackId" data-cy="entityTable">
          <td>
            <a [routerLink]="['/fiche-presence', fichePresence.id, 'view']">{{ fichePresence.id }}</a>
          </td>
          <td>{{ fichePresence.activites }}</td>
          <td>{{ fichePresence.commentaire }}</td>
          <td>{{ fichePresence.date | formatMediumDate }}</td>
          <td>
            <div *ngIf="fichePresence.consultant">
              <a [routerLink]="['/consultant', fichePresence.consultant?.id, 'view']">{{ fichePresence.consultant?.id }}</a>
            </div>
          </td>
          <td class="text-right">
            <div class="btn-group">
              <button
                type="submit"
                [routerLink]="['/fiche-presence', fichePresence.id, 'view']"
                class="btn btn-info btn-sm"
                data-cy="entityDetailsButton"
              >
                <fa-icon icon="eye"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.view">View</span>
              </button>

              <button
                type="submit"
                [routerLink]="['/fiche-presence', fichePresence.id, 'edit']"
                class="btn btn-primary btn-sm"
                data-cy="entityEditButton"
              >
                <fa-icon icon="pencil-alt"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.edit">Edit</span>
              </button>

              <button type="submit" (click)="delete(fichePresence)" class="btn btn-danger btn-sm" data-cy="entityDeleteButton">
                <fa-icon icon="times"></fa-icon>
                <span class="d-none d-md-inline" jhiTranslate="entity.action.delete">Delete</span>
              </button>

              <button class="btn btn-success">
                <fa-icon icon="save" [spin]="isLoading"></fa-icon>
                <a target="_blank" href="http://localhost:8080/api/fiche-presences/export/{{fichePresence.consultant?.id}}">
                  <span>Exporter </span>
                </a>
              </button>

            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
`

**Comment by Mariame12** [comment]
Merci beaucoup
